spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/testGaja
    hikari:
      username: root
      password: 1234

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true


#spring:
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/GajaMap
#    hikari:
#      username: postgres
#      password: manager
#
#  jpa:
#    open-in-view: false
#    hibernate:
#      ddl-auto: create
#    properties:
#      hibernate:
#        format_sql: true
#        show_sql: true
##      database-platform: org.hibernate.spatial.dialect.postgis.PostgisPG95Dialect
#      database-platform: org.hibernate.spatial.dialect.postgis.PostgisDialect
